#!/bin/sh
# Wrapper for zaproxy that disables auto-updates
export _JAVA_AWT_WM_NONREPARENTING=1 # Fix for tiling WMs
export AWT_TOOLKIT=MToolkit # Alternative Java toolkit
exec /usr/share/zaproxy/zap.sh \
    -config start.checkForUpdates=false \
    -config start.checkAddonUpdates=false \
    -config installer.downloadNewRelease=false \
    -config installer.installAddons=false \
    -config installer.installScannerRules=false \
    -config installer.reportNewAddons=false \
    "$@"
